name: Run Laravel Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel_eee
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_eee
      DB_USERNAME: root
      DB_PASSWORD: ""
      APP_ENV: testing
      APP_KEY: base64:jINuSo+8vv5p2ryWZpJKmAtD5OvHBMbmlV7XnQV+MSQ=
      CACHE_DRIVER: database
      SESSION_DRIVER: database
      QUEUE_CONNECTION: sync
      FILESYSTEM_DISK: public

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, xml, fileinfo, pdo_mysql, redis
          coverage: none

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Copy .env
        run: cp .env.example .env || cp .env .env

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Generate key (если не прописан)
        run: php artisan key:generate --force || true

      - name: Run migrations and seed
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Run tests
        run: php artisan test --parallel --stop-on-failure
